import type { MetadataRoute } from "next";

// Web app manifest — makes MyFolio installable ("Install this site as an app"
// on desktop, "Add to Home Screen" on mobile) with a standalone window, brand
// theme color, and the generated "M" icon. Auto-linked by Next.js.
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "MyFolio",
    short_name: "MyFolio",
    description: "Personal investment portfolio tracker",
    start_url: "/",
    display: "standalone",
    background_color: "#0e0e11",
    theme_color: "#ff385c",
    icons: [
      // Generated by src/app/icon.tsx (served at /icon). Full-bleed with the
      // "M" inside the safe zone, so it works as both a normal and maskable icon.
      {
        src: "/icon",
        sizes: "512x512",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icon",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
  };
}
